### ISSUE TITLE
Failed to connect to device

### ISSUE THREAD

**Issue by FunBoY7** [Lrdsnow/EUEnabler#10]
![image](https://github.com/user-attachments/assets/e6542f14-e5cc-4c00-be64-15a25d83c58d)
i dont have apple apps from microsoft store,itunes see my iphone, what can i do?

**Comment by Ratkingzzzz** [comment]
for me i just uninstalled itunes on my pc and pretty much all apple apps, if u dont know you can go to installed apps in settings and then just search "apple"
