### ISSUE TITLE
FAILED TO CONNECT TO DEVICE

### ISSUE THREAD

**Issue by SilverKnot** [Lrdsnow/EUEnabler#12]
**Failed to connect to device, if you are on windows ensure you dont have any app made by apple installed from the microsoft store and ensure your device is recognized by iTunes**

MacOS 15.1 Sequoia, error does not make sense, it works with nugget-iOS.

**Comment by bao3** [comment]
Same issue

**Comment by The1Day** [comment]
Same issue
