### ISSUE TITLE
No Module Named 'pymobiledevice3'

### ISSUE THREAD

**Issue by Cookieki** [Lrdsnow/EUEnabler#13]
When i try to run the app.py file I get the error "ModuleNotFoundError: No module named 'pymobiledevice3'". I have tried downloading pymobiledevice multiple times and i have gotten a successful download every time, but i continue to receive the error.

**Comment by ars-fr** [comment]
> When i try to run the app.py file I get the error "ModuleNotFoundError: No module named 'pymobiledevice3'". I have tried downloading pymobiledevice multiple times and i have gotten a successful download every time, but i continue to receive the error.

you need to get pymobiledevice3 not pymobiledevice
