### ISSUE TITLE
Cant Connect to Iphone

### ISSUE THREAD

**Issue by HxHL** [Lrdsnow/EUEnabler#14]
Connected Properly on Nugget Ios but i cant get it to connect on this. is this most recent update bugged?

![image](https://github.com/user-attachments/assets/b30f1f6b-eb99-416c-8352-5b155a811d4d)

**Comment by goof320** [comment]
can't connect either, on macOS sonoma 14.5. couldn't on the previous update either, nugget works fine (but eupatcher in nugget doesn't work >.>) exact same message as yours

**Comment by HxHL** [comment]
and yes im using external itunes version

**Comment by HxHL** [comment]
why close. wha
