### ISSUE TITLE
iPhone 12, iOS 18b8. iPhone12, iOS17.4 Not Working

### ISSUE THREAD

**Issue by rkinlen** [Lrdsnow/EUEnabler#4]
After trying both methods with both phones in the UK it fails to work even after successful messages.

iPhone 12, iOS 18b8
iPhone12, iOS17.4
Windows 10

**Comment by RisingGlitch** [comment]
"IF IT DOES NOT WORK THE FIRST TIME IT WILL NOT WORK FOR YOU"

that line should tell you everything
