### ISSUE TITLE
Which region do I select?

### ISSUE THREAD

**Issue by TheLostMeme** [Lrdsnow/EUEnabler#5]
iPad 9 on 17.5.1, I just ran this and rebooted my device and it's asking me what my region is. Do I just put tap "United States" since I'm from the US? I already tried this a couple times and it doesn't seem to have worked unless I'm doing something wrong.

**Comment by roundedrectangle** [comment]
Type `US` (two letters) and press Enter when asked to enter the region code. This method doesn't work on many devices, it is normal. If you typed the two letter code and tried both methods, consider closing the issue. Also try deleting the folder `EUEnabler` in your home/user folder and re-running the command `git clone https://github.com/Lrdsnow/EUEnabler.git`.
