### ISSUE TITLE
[FEATURE REQUEST] Enable region locked iOS features in the EU 

### ISSUE THREAD

**Issue by Rastafabisch** [Lrdsnow/EUEnabler#7]
II just stumbled upon your project by accident.
After examining [Config.plist](https://github.com/Lrdsnow/EUEnabler/blob/main/Config.plist) and [eligibility.plist](https://github.com/Lrdsnow/EUEnabler/blob/main/eligibility.plist) I think functionality wise it could basically [unlock](https://github.com/straight-tamago/misakaX/issues/56) just about any region locked iOS feature, though I'm not really firm enough to conclude this for sure when looking at the 

So I wonder if this could be used to unlock iPhone Mirroring and/or Apple Intelligence for EU users, where those features are infamously blocked.

**Comment by cupboardunderscore** [comment]
Hi, i’d like to add to this:
Live Voicemail is disabled in my region (CZ - latest ios 18 dev beta) and it’d be nice if it could be enabled with this tool without needing to change the phone’s region
