### ISSUE TITLE
Failed to connect to device.. but iTunes and sideloadly both recognise the device 

### ISSUE THREAD

**Issue by Optimuspime123** [Lrdsnow/EUEnabler#8]
Hi, I’m on iPhone 14 Pro iOS 18.0 db6 , iTunes (from the web) for windows and Sideloadly both recognise my device but this says Failed to connect to device.. 

I even cleared trusted computers and trusted mine again.. is it possible I’m missing something or I’m just out of luck?

**Comment by Optimuspime123** [comment]
Also, pymobiledevice3 shows it too via `usbmux list`

**Comment by DefaultBanda** [comment]
Have the same problem, also tried on a Mac running Sonama and got the same error

**Comment by Optimuspime123** [comment]
![image](https://github.com/user-attachments/assets/e5cb0a16-4a96-4803-99b9-3777646ea070)
This is the actual error I get, so I don't think the issue is with device connection but something to do with the backup location..?

**Comment by DefaultBanda** [comment]
Using Nugget Worked for me

**Comment by Runixe786** [comment]
> Using Nugget Worked for me

Can you explain the steps ? Is there a need to modify the command or what ?

**Comment by Optimuspime123** [comment]
> > Using Nugget Worked for me
> 
> Can you explain the steps ? Is there a need to modify the command or what ?

I _think_ the issue is because the path this tool is trying to access is on a separate partition, [Nugget-iOS](https://github.com/LoveJessyChen/Nugget-iOS) has an edited version of restore.py  which apparently works?
